---
- name: Gather facts about VPC before deletion
  ec2_vpc_net_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ vpc_name }}"
  register: vpc_facts

- name: Set VPC ID fact
  set_fact:
    vpc_id: "{{ vpc_facts.vpcs[0].id }}"
    
- name: Remove Security Group
  ec2_group:
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    group_id: "{{ secgroup_id }}"
    state: absent